version: '3.8'
services:
    web:
        build: .
        entrypoint: ["/bin/sh","-c"]
        command:
            - |
               python manage.py migrate --noinput
               python daemon/memory_check_daemon.py &
               python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
