# Generated by Django 4.1.7 on 2023-03-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('surname', models.CharField(blank=True, max_length=64)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Prefer not to disclose')], default='U', max_length=1)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
    ]
