# Generated by Django 4.1.7 on 2023-03-22 05:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Prefer not to disclose')], default='U', max_length=1),
        ),
    ]
